name: List Available macOS Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  update-versions:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get macOS Versions
        run: |
          # Create versions list
          echo "VERSIONS<<EOF" >> $GITHUB_ENV
          echo "# Available macOS Versions" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          # softwareupdate --list-full-installers | grep -E "macOS.*" >> $GITHUB_ENV
          softwareupdate --list-full-installers | grep -E "macOS.*" | awk '{print $2" v"$3}' | jq -R -s -c 'split("\n")[:-1]') >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update README
        run: |
          # Create new README with updated content
          cat > README.tmp << EOL
          $(cat README.md | sed -n '1,/<!-- BEGIN MACOS VERSIONS -->/p')
          ${{ env.VERSIONS }}
          $(cat README.md | sed -n '/<!-- END MACOS VERSIONS -->/,$p')
          EOL
          mv README.tmp README.md


