name: List Available macOS Releases
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"
    
jobs:
  update-versions:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Initialize README if needed
        run: |
          if [ ! -f README.md ]; then
            echo "# macOS Versions" > README.md
            echo "" >> README.md
            echo "<!-- BEGIN MACOS VERSIONS -->" >> README.md
            echo "<!-- END MACOS VERSIONS -->" >> README.md
          fi

      - name: Get macOS Versions
        run: |
          {
            echo "<!-- BEGIN MACOS VERSIONS -->"
            echo "<details>"
            echo "<summary>🖥️ Available macOS Versions</summary>"
            echo ""
            softwareupdate --list-full-installers | grep -E "macOS.*" | while read -r line; do
              name=$(echo "$line" | grep -o 'Title: macOS [^,]*' | cut -d' ' -f3)
              version=$(echo "$line" | grep -o 'Version: [^,]*' | cut -d' ' -f2)
              build=$(echo "$line" | grep -o 'Build: [^,]*' | cut -d' ' -f2)
              size_kb=$(echo "$line" | grep -o 'Size: [0-9]*' | cut -d' ' -f2)
              size_gb=$(echo "scale=2; $size_kb/1024/1024" | bc)
              echo "* macOS $name $version ($build) - ${size_gb}GB"
            done
            echo ""
            echo "</details>"
            echo "<!-- END MACOS VERSIONS -->"
          } > versions.tmp

      - name: Update README
        run: |
          cp versions.tmp README.md
          rm versions.tmp

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update macOS versions list" || exit 0
          git push

         



