name: List Available macOS Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  update-versions:
    update-versions:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      
      - name: Get macOS Versions
        id: versions
        run: |
          echo "VERSIONS_TABLE<<EOF" >> $GITHUB_ENV
          echo "| macOS Version | Build Number | Release Date |" >> $GITHUB_ENV
          echo "|--------------|--------------|--------------|" >> $GITHUB_ENV
          softwareupdate --list-full-installers | grep -E "macOS.*" | while read -r line; do
            version=$(echo "$line" | cut -d' ' -f2-)
            echo "| $version | - | $(date +%Y-%m-%d) |" >> $GITHUB_ENV
          done
          echo "EOF" >> $GITHUB_ENV

      - name: Update README
        run: |
          awk '/<!-- BEGIN MACOS VERSIONS -->/{p=1;print;print ENVIRON["VERSIONS_TABLE"]}!/<!-- BEGIN MACOS VERSIONS -->/{if(!p)print}/<!-- END MACOS VERSIONS -->/{p=0}' README.md > README.tmp
          mv README.tmp README.md

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update macOS versions table" || exit 0
          git push

  re-run-failed-jobs:
    runs-on: ubuntu-latest
    needs: [update-versions]
    if: always() && (needs.update-versions.result == 'failure')
    steps:
      - name: Needs Context
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: echo "$NEEDS_CONTEXT"
