name: List Available macOS Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  update-versions:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get macOS Versions
        id: versions
        run: |
          echo "VERSIONS_LIST<<EOF" >> $GITHUB_ENV
          echo "# Available macOS Versions" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          softwareupdate --list-full-installers | grep -E "macOS.*" | while read -r line; do
            echo "$line" >> $GITHUB_ENV
          done
          echo "EOF" >> $GITHUB_ENV

      - name: Update README
        run: |
          awk '/<!-- BEGIN MACOS VERSIONS -->/{p=1;print;print ENVIRON["VERSIONS_LIST"]}!/<!-- BEGIN MACOS VERSIONS -->/{if(!p)print}/<!-- END MACOS VERSIONS -->/{p=0}' README.md > README.tmp
          mv README.tmp README.md

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update macOS versions list" || exit 0
          git push
